spring.application.name=carwash

# Configuracion PostgreSQL - Render
spring.datasource.url=jdbc:postgresql://dpg-d7lf4agjs32c73851fo0-a.oregon-postgres.render.com:5432/lavado_5uyh?sslmode=require
spring.datasource.username=lavado_user
spring.datasource.password=huZwL00uFxJyt916kV8l1CKpR2rNe02m
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
